export const GET_USERS = "GET_USERS";
//export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const CLEAR_USER = "CLEAR_USER";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const SHOW_USER = "SHOW_USER";
//export const SHOW_USER_START = "SHOW_USER_START";
export const SHOW_USER_SUCCESS = "SHOW_USER_SUCCESS";
export const SHOW_USER_ERROR = "SHOW_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
//export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
//export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const DELETE_ALL_USER = "DELETE_ALL_USER";
//export const DELETE_ALL_USER_START = "DELETE_ALL_USER_START";
export const DELETE_ALL_USER_SUCCESS = "DELETE_ALL_USER_SUCCESS";
export const DELETE_ALL_USER_ERROR = "DELETE_ALL_USER_ERROR";

export const ADMIN_LOGIN = 'ADMIN_LOGIN'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR'

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'
export const ADMIN_LOGOUT_ERROR = 'ADMIN_LOGOUT_ERROR'